SELECT N, 'Leaf' as Typ
FROM BST
WHERE N NOT IN (SELECT P FROM BST WHERE P IS NOT NULL)

UNION

SELECT N, 'Root' as Typ
FROM BST
WHERE P IS NULL

UNION

SELECT N, 'Inner' as Typ
FROM BST
WHERE N IN (
    SELECT P
    FROM BST
    WHERE P NOT IN (SELECT N FROM BST WHERE P IS NULL)
)

ORDER BY N;